### ISSUE TITLE
Conflicting styles?

### ISSUE THREAD

**Issue by mleone11** [alphapapa/solarized-everything-css#42]
When I activated all of the solarized light themes via Stylish (I'm using Chrome) the margins/spacing/alignment on Google gets messed up, pretty much making it unusable. I found that disabling the bigblow css theme sets everything back to normal.

**Comment by jgkamat** [comment]
How exactly are you enabling the stylesheet (I'm a bit unfamiliar with how stylish works).

Recently, we made an update to remove the bigblow stylesheet from the [all-styles](https://github.com/alphapapa/solarized-everything-css/blob/master/css/solarized-dark/solarized-dark-all-sites.css) stylesheets, so if you use the newer stylesheets, they should work fine (unless you are using the bigblow css stylesheet on every site). 

If you pulled them from a website instead of from this repo, that website might need updating. Also see #37

**Comment by mleone11** [comment]
Just today I downloaded Stylish (v 2.0.2) and the solarized-light css files and imported them into my Stylish "library". They get enabled automatically after doing that and you can toggle them on/off from within the toolbar. I'm assuming that each active style sheet gets applied to the active browser window, so that's why I think there must be some sort of discrepancy between two (or more) style sheets.

If it's not intended to have the all-styles sheet enabled at the same time as any of the others then I apologize for my oversight.

**Comment by jgkamat** [comment]
Where are you getting the files from, are you pulling it from [this file](https://raw.githubusercontent.com/alphapapa/solarized-everything-css/master/css/solarized-light/solarized-light-all-sites.css)?

I just tried with stylus (copy pasting that file into a style), and I get the following results:

![2018-05-31-104237_1920x1080_scrot](https://user-images.githubusercontent.com/4349709/40798239-0ec0270c-64fa-11e8-82f1-4a48ff0016a1.png)
![2018-05-31-104253_1920x1080_scrot](https://user-images.githubusercontent.com/4349709/40798247-1175d0f0-64fa-11e8-8c4a-c123540945e3.png)
![2018-05-31-104314_1920x1080_scrot](https://user-images.githubusercontent.com/4349709/40798261-1afd882a-64fa-11e8-95c7-4a67a827b6b9.png)

If you have the bigblow stylesheet active on top of the all-sites one, do expect to see this. I'm not sure what would happen if you enabled the all-sites stylesheet and, for example, the google one, I would assume they would override each other and nothing would change.

**Comment by mleone11** [comment]
Oh, I understand what you're saying- bigblow was removed from within all-sites because of some css conflict, and I should not have both all-sites and bigblow enabled (separately) for that same reason. Again, sorry for my oversight!

After re-reading the installation part of the readme my only suggestion is to explicitly say under the first (all-sites) bullet point that if using the all-sites file, do not use any of the individual/specific ones as it's possible that there could be conflicts

**Comment by jgkamat** [comment]
Yup, glad you were able to get that working! One thing to note is that because all-sites is just all the sites we have crammed together (except bigblow), you might have some small issues on some sites. However, I haven't noticed any issues, and I've been using it for quite a while. I'll close this issue now, let us know if you need any more help :)
